-- 2022년 1월의 도서 판매 데이터 기준으로 
-- 저자 별, 카테고리 별 매출액 
-- 저자 ID, 저자명, 카테고리, 매출액 리스트 출력 
-- 저자 ID 오름차순 & 카테고리 내림차순 
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
       SUM(B.PRICE * BS.SALES) AS 'TOTAL_SALES'
FROM BOOK_SALES BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE BS.SALES_DATE BETWEEN DATE '2022-01-01' AND DATE '2022-01-31'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC; 