-- 2022년 3월 오프라인/온라인 상품의 판매날짜, 상품ID, 유저ID, 판매량 출력
-- OFFLINE_SALE의 USER_ID는 NULL로 표시 
-- 판매일 오름차순, 상품 ID 오름차순, 유저 ID 오름차순 
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT 
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-03"
UNION ALL 
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT 
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-03"
ORDER BY 1, 2, 3;