-- 서울에 위치한 식당 ID, 이름, 음식종류, 즐겨찾기수, 주소, 리뷰 평균 조회
-- 리뷰 평균 : 소수점 세 번째 자리에서 반올림 
-- 평균점수를 기준으로 내림차순, 즐겨찾기수 내림차순 정렬
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;