-- 기간 : 22년 8월 ~ 22년 10월
-- 총 대여 횟수 5회 이상인 자동차 
-- 월간 자동차별 총 대여횟수 (0회일 경우 해당 월에서 제외)
-- 월 기준 오름차순 & 자동차 ID 기준 내림차순 
SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH,
       CAR_ID,
       COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
  AND CAR_ID IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN DATE '2022-08-01' AND DATE '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
  )
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
HAVING COUNT(*) > 0
ORDER BY EXTRACT(MONTH FROM START_DATE), CAR_ID DESC;
