-- 성분 타입 & 성분 타입에 대한 아이스크림의 총 주문량 
-- 총 주문량이 작은 순서대로 조회 
SELECT INGREDIENT_TYPE,
       SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO I
JOIN FIRST_HALF F ON I.FLAVOR = F.FLAVOR
GROUP BY INGREDIENT_TYPE;