-- 2022년 1월의 카테고리 별 도서 판매량 합산
-- 카테고리, 총 판매량 리스트 
-- 카테고리명 기준 오름차순 정렬
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;